#!/usr/bin/env php
<?php
/**
 * Arikaim
 *
 * @link        http://www.arikaim.com
 * @copyright   Copyright (c) 2017-2019 Konstantin Atanasov <info@arikaim.com>
 * @license     http://www.arikaim.com/license
 * 
*/
define('ARIKAIM_ROOT_PATH',__DIR__);

include_once "vendor/autoload.php";

use Arikaim\Core\System\Console\Application;
use Arikaim\Core\Arikaim;

Arikaim::init(false);

$application = new Application();
$application->run();
