#!/usr/bin/env php
<?php
/**
 * Arikaim Server
 *
 * @link        http://www.arikaim.com
 * @copyright   Copyright (c) 2017-2018 Konstantin Atanasov <info@arikaim.com>
 * @license     http://www.arikaim.com/license.html
 * 
*/
define('ROOT_PATH',__DIR__);

include_once "vendor/autoload.php";
include_once "arikaim/core/System/ClassLoader.php";
include_once "arikaim/core/Arikaim.php";

use Arikaim\Core\Arikaim;
use Arikaim\Core\Server\ArikaimServerFactory;

Arikaim::systemInit(1,true);

$server = ArikaimServerFactory::create();

if (\is_object($server) == false) {
    echo 'ERROR: Server options not valid! ' . PHP_EOL;
    exit();
}

// boot server
$server->boot();
// run
$server->run();
